version: '3'
services:
  chatbot:
    image: 7940image4
    environment:
      ACCESS_TOKEN: 6125927916:AAEVxbVhDzAfdE0zpzKCwPk3kXlYwXQdHGE
      HOST: redis
      PASSWORD: comp7940passwordlab8
      REDISPORT: 6379
    entrypoint: python chatbot.py
    depends_on:
      - redis
  redis:
    image: redis
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    command: ["/usr/local/etc/redis/redis.conf"]