version: '3'
services:
  chatbot:
    image: 7940image
    environment:
      ACCESS_TOKEN: 6125927916:AAFDzHdPbxjCdTttrxmOAUmLICwL7kLE-AI
      HOST: chatbart.redis.cache.windows.net
      PASSWORD: LDyPk3e3HDX5uR7ZL8fwf55nFeBuoxZFeAzCaM7Hw3o=
      REDISPORT: 6380
      GPTAPIKEY: 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
    entrypoint: python chatbot.py
